### ISSUE TITLE
How to use as a gating metric

### ISSUE THREAD

**Issue by bpracht** [thsaravana/jacoco-playground#14]
I'm new to workflows and the best I'm able to get is the code coverage result. I'd like to be able to block a PR merge if the coverage is too low. How do I get it to raise an appropriate status/event or whatever it's called to block this?

**Comment by thsaravana** [comment]
@bpracht You can add an additional step to check if the output coverage meets the threshold. You can refer this PR for how to do this: https://github.com/thsaravana/jacoco-playground/pull/16
